name: deploy gh-pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and deploy gh-pages
    env:
      MY_SECRET   : ${{secrets.commit_secret}}
      USER_NAME   : githubaction
      USER_EMAIL  : githubaction@fake.com
      PUBLISH_DIR : ./
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn
      run: |
        yarn
    - name: yarn page
      run: |
        yarn page
